
    create table tb_endereco (
       id int8 generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        localidade varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        uf varchar(255),
        primary key (id)
    );

    create table tb_role (
       id int8 generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table tb_usuario (
       id int8 generated by default as identity,
        cpf varchar(255),
        data_nascimento timestamp,
        email varchar(255),
        nome varchar(255),
        password varchar(255),
        role_id int8,
        primary key (id)
    );

    create table tb_usuario_endereco (
       usuario_id int8 not null,
        endereco_id int8 not null,
        primary key (usuario_id, endereco_id)
    );

    alter table if exists tb_usuario 
       add constraint UK_594wib8ansybtilla48x7vdld unique (cpf);

    alter table if exists tb_usuario 
       add constraint UK_spmnyb4dsul95fjmr5kmdmvub unique (email);

    alter table if exists tb_usuario 
       add constraint FK9dplumgdbm9264hcb01kxec98 
       foreign key (role_id) 
       references tb_role;

    alter table if exists tb_usuario_endereco 
       add constraint FKaue719hqmvyjtgmtwpc034fvt 
       foreign key (endereco_id) 
       references tb_endereco;

    alter table if exists tb_usuario_endereco 
       add constraint FK6wxi3lqtj05gk1ysggckuuy59 
       foreign key (usuario_id) 
       references tb_usuario;
